# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-07 08:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180807_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 7, 8, 10, 28, 827492, tzinfo=utc)),
        ),
    ]
